### ISSUE TITLE
project name

### ISSUE THREAD

**Issue by pavoljuhas** [diffpy/diffpy.mappdf#5]
@CJ-Wright @sbillinge - please consider renaming this project to diffpy.mappdf and rearrange the source code to use the same Python import name (i.e., `import diffpy.mappdf`.  This will make it consistent with other diffpy packages and will avoid confusion with software for rendering maps as PDF documents (https://github.com/systemed/MapPDF).

**Comment by chiahaoliu** [comment]
@pavoljuhas I have renamed the project name. Thanks for the feedback.

**Comment by pavoljuhas** [comment]
Looks good to me, thank you for fixing.
