### ISSUE TITLE
excessively large example files in source repository

### ISSUE THREAD

**Issue by pavoljuhas** [diffpy/diffpy.mappdf#6]
Commit b62b7ffb651ff3a40ffa3b11e919f8f45ef1bc41 introduced some very large example files:

```sh
$ du -sh mappdf/map_PDF_example_data 
102M	mappdf/map_PDF_example_data
```

This makes the source repo unwieldy, because even if removed, the contain permanently remains in the git history.

Is it critical to include and distribute these files with the package?

Please consider some other solution for working with huge data, here are some options:

1. keep them in dropbox or similar service and download once on demand `wget --timestamping URLToBigFile`.
2. keep them in a separate git repo and add them as [git submodule](https://git-scm.com/docs/git-submodule).
3. store them using GitHub LFS extension - https://git-lfs.github.com.

I'd recommend to rebase this repo to permanently remove the huge data.  The project is small enough that this should not cause much disruption.

**Comment by chiahaoliu** [comment]
After confirming with the author, the directory is required for demonstration, except for one big file (85M) which is the core of this problem.

Instead of completely rebasing the repo, is it possible to do ``git filter-branch`` as from the
[github doc](https://help.github.com/articles/removing-sensitive-data-from-a-repository/)?

**Comment by pavoljuhas** [comment]
> the directory is required for demonstration, except for one big file (85M) which is the core of this problem.

That still leaves 17M of demo data in a package that otherwise has ~80K of source code.
Would it be possible to do a demo on a smaller set of data or collate the datafiles to one
HDF file instead?

> Instead of completely rebasing the repo, is it possible to do git filter-branch as from the
github doc?

Sure, use whichever is more convenient.  However, either way you will get master branch that is split from the current master at the commit that added the big file.  Any further work must be based on the new master and must not merge the old branch with huge file.

**Comment by pavoljuhas** [comment]
BTW, please git-filter away also the 'docs/_build' directory.  Let's clean up completely if we already get into that.

**Comment by chiahaoliu** [comment]
@pavoljuhas I've cleaned the history by fully rebasing and now required files for demo folder is reduced to the size of 6.2M (phew~). 

It might increase a bit after including Gr data corresponding to 136 Iq files but shouldn't be too much.

One point we might need your input. What's is the best way of including ``FitRecipe`` objects to the demo? Would pickle a good approach? Thanks.

**Comment by sbillinge** [comment]
With this experience we may think in the future to separate code and
datasets. Perhaps in general we should publish data to an archival data
repository and give it a doi, then give instructions to people how to get
the data from wherever it is. It could be zenodo, but I found that to be
not so intuitive to use. There is also the one at NIST or the other one, I
forgot where....

**Comment by pavoljuhas** [comment]
> I've cleaned the history by fully rebasing and now required files for demo folder is reduced to the size of 6.2M (phew~).

I cannot quite see it.  The disk usage actually increased in the new master:
```sh
$ git checkout d50f32ea       # old
$ du -sh mappdf
102M	mappdf

$ git checkout e364d385      # new
$ du -sh mappdf
118M	mappdf
```

**Comment by pavoljuhas** [comment]
> What's is the best way of including FitRecipe objects to the demo? Would pickle a good approach? 

Pickles are very fragile and bound to break in the future.  They don't work if recipe contains pyobjcryst Crystal objects.  I would only use pickles for a short term persistence, but definitely not include in a repo data.

One approach would be to write a factory function/class which can generate FitRecipe as needed.  I have put together a prototype of such thing at https://github.com/pavoljuhas/pdfrecipebuilder.git, but I am not sure if this would work for your use case.

**Comment by chiahaoliu** [comment]
I further cleaned the repo. Basically I wiped out everything I can in order to get us a clean start but the repo is still at the size of 37Mb which is mostly in ``.git/`` 
````
$ git checkout 4ca496aa
$ du -sh .git
37M	.git
````
Is there any suggestion on this situation? (I already did ``git gc``)

I am also worried if the huge ``.git`` situation is due to the fact that this repo is moved from ``gitlab`` and it contains lengthy history.

**Comment by pavoljuhas** [comment]
> Is there any suggestion on this situation? (I already did git gc)

Looks like there are still big data in the history - 290380db67c1cc537fcc75dd23a4787d7ee8c629.

Let me try to clean it up - I will post here when I have a scrubbed branch ready.

**Comment by chiahaoliu** [comment]
Thanks for helping Pavol!

I think those files are from ``gitlab`` history (this repo was ``analysis``). I have all files backed up as well.

**Comment by pavoljuhas** [comment]
Hi Tim - here is my version `master-1-trimmed` thinned down from your earlier commit e364d385:

```sh
$ git clone --branch=master-1-trimmed --single-branch \
    https://github.com/pavoljuhas/mappdf.git /tmp/mappdf
$ du -sh /tmp/mappdf/.git
788K	/tmp/mappdf/.git
```

If that looks OK, you can force-push master-1-trimmed to diffpy/mappdf master.  BTW, you will also need to update the release tags so they point to the new branch.

**Comment by chiahaoliu** [comment]
Hi Pavol,

Thanks! That cleaned repo looks good and I've faced push to the master. However, I am thinking if the best practice is to start everything from scratch so that we can have the repo name correctly set up and proceed each step carefully (like handling the example files etc).

Does it make sense?

**Comment by pavoljuhas** [comment]
Hi Tim, Either way is going to be a bit confusing if you keep project history (i.e., the master-1-trimmed commits).  If you start a new project, the PR-s will get number from 1 and will not match the recorded history.  You can also rename the current repo and GitHub will for some time do redirects `old-name --> new-name`.  You will need to check that any future merge (or PR) does not re-introduce the old commits, but that should be easy to see from how many commits are included in the PR.

BTW, there is one more thing to finish the clean up of the current repo.  The tags need to be updated so they point to the new branch  - I have already done so in my fork.
```sh
git fetch --no-tags https://github.com/pavoljuhas/mappdf.git tag 0.1.1 tag 0.1.2
git push origin --force --dry-run tag 0.1.1 tag 0.1.2
```

If all is good, a fresh clone of the main repo should be of small size.

**Comment by chiahaoliu** [comment]
@pavoljuhas I have pushed the cleaned repo, along with additional cleaning.

Now a fresh clone of this repo is 356K

````
timothyliu@172-30-48-63:~/Repo/mappdf$ du -sh
356K	.
````

and we should be able to have a fresh(er) start.

**Comment by pavoljuhas** [comment]
@chiahaoliu - I can't see any python files - is that intended?

Also, the tags at https://github.com/diffpy/mappdf/releases are on the old branch.  Please update them to point to the new commits or delete them altogether.

**Comment by CJ-Wright** [comment]
@chiahaoliu you may still be able to use `rever -u tag` to revert the tag, maybe?

**Comment by chiahaoliu** [comment]
@pavoljuhas yes, I deleted all the python files on purpose as I want to have a clean start for this repo.

I also deleted old releases tag. Please let me know if there more to do. Thanks.

**Comment by pavoljuhas** [comment]
@chiahaoliu - it seems that tags are still on the obsolete branch:
```sh
$ git clone https://github.com/diffpy/diffpy.mappdf.git /tmp/x1
$ cd /tmp/x1
$ git log --graph --oneline --tags master --author-date-order --decorate --first-parent
* 7d48916 (HEAD -> master, origin/master, origin/HEAD) BLD: add _build/ into .gitignore
* a888b68 CLN: update gitignore
| * 1cbd24d (tag: 0.1.2) Updated CHANGELOG for 0.1.2
* | 53f8220 Updated CHANGELOG for 0.1.2
| * 366b3a2 bumped version to 0.1.2
* | e86bb1e bumped version to 0.1.2
| * 2ce1b41 FIX: redo news template with CJ
* | 440f417 FIX: redo news template with CJ
| * f74e3f0 (tag: 0.1.1) Updated CHANGELOG for 0.1.1
* | f90502b Updated CHANGELOG for 0.1.1
| * b509c91 bumped version to 0.1.1
* | 616ecb2 bumped version to 0.1.1
| * f41e415 MNT: exclude pypi, conda for test run
* | 9f118d2 MNT: exclude pypi, conda for test run
| * 7db788a Merge pull request #2 from chiahaoliu/master
* | 1a32cfb Merge pull request #2 from chiahaoliu/master
|/  
* f1e6344 BLD: draft on initial package structure
* 7ddb8da Add readme.md
```

Please fix them up as follows:
```sh
$ git tag -f 0.1.2 53f8220
Updated tag '0.1.2' (was 1cbd24d)
$ git tag -f 0.1.1 f90502b
Updated tag '0.1.1' (was f74e3f0)

# verify tags are now on master
$ git branch --contains=0.1.1
* master
$ git branch --contains=0.1.2
* master

# fix tags in the main repo
$ git push --force --tags origin

# verify tags are the same in origin and in the local repo:
$ git ls-remote --tags origin
$ git ls-remote --tags .
```

For the future I would recommend to use signed tags, instead of light-weight name-only tags.
The signed tags have information on who has created the tag, the date of tagging, comments describing the tag, and also allow to verify your identity.  Please see https://github.com/diffpy/diffpy.srreal/tags and click on `...` near `v1.2` for an example of a signed tag.  (You can also do `git show v1.2` in the srreal repo.)

**Comment by pavoljuhas** [comment]
Tags are fixed, thank you @chiahaoliu !
